const mongoose = require('mongoose');

/**
 * A user's request for a temporary increase of their daily AI budget
 * (services/aiBudget.js). Typically raised mid-import when the shared
 * per-user daily budget ran out and rows fell back to fuzzy matching
 * (aiSkipped). An admin reviews it and either approves (which writes a
 * time-boxed `aiBudgetOverride` onto the User document) or denies it.
 *
 * GDPR: registered in services/userDataRegistry.js (deleted with the account,
 * decidedBy cleared off other users' requests when the deciding admin is
 * erased, included in the /me/export payload). Rows auto-expire after 180
 * days via the TTL index on createdAt — long enough for an audit trail,
 * short enough to not retain reasons (free text) indefinitely.
 */
const RETENTION_DAYS = 180;

const aiBudgetRequestSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true,
  },
  // User-supplied or auto-generated by the importer,
  // e.g. "Importing 1,500 bottles — 620 remaining".
  reason: {
    type: String,
    trim: true,
    maxlength: [500, 'Reason too long'],
    default: '',
  },
  // Optional metadata snapshot from the requesting context.
  requestedContext: {
    pendingRows: { type: Number, default: null },
  },
  status: {
    type: String,
    enum: ['pending', 'approved', 'denied'],
    default: 'pending',
    index: true,
  },
  decidedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
  decidedAt: { type: Date, default: null },
  // Set on approval — mirrors what was written to User.aiBudgetOverride.
  grantedMax:   { type: Number, default: null },
  grantedUntil: { type: Date, default: null },
}, { timestamps: true });

// At most ONE pending request per user — makes the route's 409 race-safe
// (two concurrent POSTs can't both insert a pending row). Compound with
// status so it doesn't duplicate the field-level `index: true` on user.
aiBudgetRequestSchema.index(
  { user: 1, status: 1 },
  { unique: true, partialFilterExpression: { status: 'pending' } }
);

// 180-day retention (TTL) — decided requests are an audit trail, not
// permanent records.
aiBudgetRequestSchema.index({ createdAt: 1 }, { expireAfterSeconds: RETENTION_DAYS * 24 * 60 * 60 });

module.exports = mongoose.model('AiBudgetRequest', aiBudgetRequestSchema);
