import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { BETA_BELOW, localeStatus } from '../src/locales/coverage.js';

const VIRTUAL_ID = 'virtual:locale-coverage';
const RESOLVED_ID = `\0${VIRTUAL_ID}`;

const here = path.dirname(fileURLToPath(import.meta.url));

/**
 * Emits per-locale translation coverage as a virtual module.
 *
 * Computed at build time, deliberately: a checked-in coverage.json would be
 * stale after every Weblate merge (its PRs touch the locale files and nothing
 * else), and the alternative — counting keys at runtime — would mean eagerly
 * loading every locale bundle just to render a dropdown, which is exactly what
 * the lazy loading in src/i18n.js exists to avoid. Only the counts ship.
 */
export default function localeCoverage({ localesDir = path.resolve(here, '../src/locales') } = {}) {
  const read = (code) =>
    JSON.parse(fs.readFileSync(path.join(localesDir, code, 'translation.json'), 'utf8'));

  const localeCodes = () =>
    fs
      .readdirSync(localesDir, { withFileTypes: true })
      .filter((e) => e.isDirectory() && fs.existsSync(path.join(localesDir, e.name, 'translation.json')))
      .map((e) => e.name)
      .sort();

  return {
    name: 'cellarion:locale-coverage',

    resolveId(id) {
      return id === VIRTUAL_ID ? RESOLVED_ID : null;
    },

    load(id) {
      if (id !== RESOLVED_ID) return null;

      const codes = localeCodes();
      if (!codes.includes('en')) {
        this.error(`locale-coverage: no en/translation.json under ${localesDir}`);
      }

      const en = read('en');
      const locales = codes.map((code) => {
        // English is the source language: complete by definition, and counting
        // it against itself would be circular.
        if (code === 'en') {
          const { total } = localeStatus('en', en, en);
          return { code: 'en', translated: total, total, ratio: 1, beta: false };
        }
        return localeStatus(code, en, read(code));
      });

      // Rebuild when a translator's PR lands (dev server) or on the next build.
      for (const code of codes) {
        this.addWatchFile(path.join(localesDir, code, 'translation.json'));
      }

      return [
        `// generated by vite-plugins/localeCoverage.js — do not edit`,
        `export const LOCALES = ${JSON.stringify(locales, null, 2)};`,
        `export const BETA_BELOW = ${BETA_BELOW};`,
        `export const LOCALE_CODES = ${JSON.stringify(locales.map((l) => l.code))};`,
        `export const SHIPPED_CODES = ${JSON.stringify(locales.filter((l) => !l.beta).map((l) => l.code))};`,
      ].join('\n');
    },

    // A changed translation.json must invalidate the virtual module, not just
    // the file itself — otherwise the dev server keeps serving stale counts.
    handleHotUpdate({ file, server }) {
      if (!file.replaceAll('\\', '/').includes('/locales/') || !file.endsWith('translation.json')) return;
      const mod = server.moduleGraph.getModuleById(RESOLVED_ID);
      if (mod) server.moduleGraph.invalidateModule(mod);
    },
  };
}
